POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "hazeem08",
  "password": "0987654321"
}

############################ NEW USER LOGIN
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Azz",
  "password": "zaaa"
}
################################ ADMIN LOGIN

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

######################### SECURITY
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "security",
  "password": "123456789"
}
############################### REGISTER USER BY ADMIN
POST http://localhost:4000/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6IkF6eiIsInBhc3N3b3JkIjoiemFhYSIsIm5hbWUiOiJBbG1pbmEgZ2F6aSIsImVtYWlsIjoibmV3dXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJfaWQiOiI2NTg5OTQzMWZiYTI2ZTE4MTkxNjU0YjUifSwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDM1MTUyNzAsImV4cCI6MTcwMzUxNzA3MH0.E5Osu-EK0fc5wBYOKPNNxfsLISBcMfMfOuGfvwqVFe8

{
  "username": "Azz",
  "password": "zaaa",
  "name": "Almina gazi",
  "email": "newuser2@gmail.com",
  "role": "user"
}

############################### ADD VISITOR BY USER
POST http://localhost:4000/addvisitors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6IkF6eiIsInBhc3N3b3JkIjoiemFhYSIsIm5hbWUiOiJBbG1pbmEgZ2F6aSIsImVtYWlsIjoibmV3dXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJfaWQiOiI2NTg5OTQzMWZiYTI2ZTE4MTkxNjU0YjUifSwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDM1MTUyNzAsImV4cCI6MTcwMzUxNzA3MH0.E5Osu-EK0fc5wBYOKPNNxfsLISBcMfMfOuGfvwqVFe8

{
  "visitorname": "Ahmad Ahmad",
  "id": "01214215212",
  "visitorpass": "Ahmad Ahmad5678",
  "phoneNumber": "0142464274",
  "email": "Ahmad@gmail.com",
  "appointmentDate": "2024-06-227",
  "carPlate": "AMY4127",
  "purpose": "VIP",
  "destination": "Museum",
  "registeredBy": "Almina gazi"
}

##################### VISITOR CHECKIN BY SECURITY
POST http://localhost:4000/checkin  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6InNlY3VyaXR5IiwicGFzc3dvcmQiOiIxMjM0NTY3ODkiLCJuYW1lIjoiUGFrIEd1YXJkIiwiZW1haWwiOiJQYWsgZ3VhcmQuY29tIiwicm9sZSI6InNlY3VyaXR5IiwiX2lkIjoiNjU4OTg1Njk1ZjQ3MjEzMzZmYWI3MTEzIn0sInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTcwMzUxMTk1NiwiZXhwIjoxNzAzNTEzNzU2fQ.V2jq0uQzzzHLdNAUHtyTNLsmAta4dM67zFOAaPW2RWo

{
  "visitorpass": "ayam1234",
  "carplate": "KER8195"
}

############################# VISITOR CHECKOUT BY SECURITY
POST http://localhost:4000/checkout 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6InNlY3VyaXR5IiwicGFzc3dvcmQiOiIxMjM0NTY3ODkiLCJuYW1lIjoiUGFrIEd1YXJkIiwiZW1haWwiOiJQYWsgZ3VhcmQuY29tIiwicm9sZSI6InNlY3VyaXR5IiwiX2lkIjoiNjU4OTg1Njk1ZjQ3MjEzMzZmYWI3MTEzIn0sInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTcwMzUxMTk1NiwiZXhwIjoxNzAzNTEzNzU2fQ.V2jq0uQzzzHLdNAUHtyTNLsmAta4dM67zFOAaPW2RWo

{
  "visitorpass": "ayam1234",
  "carplate":"KER8195"
}

############################# EDIT DATA BY USER
PATCH http://localhost:4000/editvisitor/64994ee23c9d03924720c246
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImhhemVlbTA4IiwicGFzc3dvcmQiOiIwOTg3NjU0MzIxIiwibmFtZSI6ImhhemltZmFobWkiLCJlbWFpbCI6ImhhemltanI3NjNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJfaWQiOiI2NTg5OTQyZmZiYTI2ZTE4MTkxNjU0YjIifSwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDM1MTUzNDcsImV4cCI6MTcwMzUxNzE0N30.3AJJRRvfjhxDWRm2i1ow8Gi5Ryex4LgTNtXsxrmjdb8

{
  "visitorname": "Ahmad Ahmad",
  "phoneNumber": "8555555555555555555",
  "appointmentDate": "2025-10-22"
}

###################################### DELETE DATA BY USER
DELETE http://localhost:4000/deletevisitor/64994ee23c9d03924720c246
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6ImhhemVlbTA4IiwicGFzc3dvcmQiOiIwOTg3NjU0MzIxIiwibmFtZSI6ImhhemltZmFobWkiLCJlbWFpbCI6ImhhemltanI3NjNAZ21haWwuY29tIiwicm9sZSI6InVzZXIifSwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDM2NDAzNDksImV4cCI6MTcwMzY0MjE0OX0.HbG9RKAYZ5D80ueQsuIIKtH0MlMvL-8dozzkIysKRKM


####################################### ALL VISITOR ADMIN SECURITY
GET http://localhost:4000/visitorinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6InNlY3VyaXR5IiwicGFzc3dvcmQiOiIxMjM0NTY3ODkiLCJuYW1lIjoiUGFrIEd1YXJkIiwiZW1haWwiOiJQYWsgZ3VhcmQuY29tIiwicm9sZSI6InNlY3VyaXR5IiwiX2lkIjoiNjU4OTk0MzBmYmEyNmUxODE5MTY1NGIzIn0sInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTcwMzUxNTU2MiwiZXhwIjoxNzAzNTE3MzYyfQ.vF9xaTGnD07iSgjjQgBV5XFjcWbhhcwRSW04DUII1eA

############################################ USER BY VISITOR NAME
GET http://localhost:4000/visitorinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUHJvZmlsZSI6eyJ1c2VybmFtZSI6IkF6eiIsInBhc3N3b3JkIjoiemFhYSIsIm5hbWUiOiJBbG1pbmEgZ2F6aSIsImVtYWlsIjoibmV3dXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJfaWQiOiI2NTg5OTQzMWZiYTI2ZTE4MTkxNjU0YjUifSwicm9sZSI6InVzZXIiLCJpYXQiOjE3MDM1MTU2NzEsImV4cCI6MTcwMzUxNzQ3MX0.13BOFZ-xbt7YPbO-YBn7zAJwfkf79q33xwwEB16rSOM

{
 "registeredBy": "hazeemfahmii"
}

